---
spring:
  application:
    name: pdf-merger
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
service:
  max-files: 10
gg:
  jte:
    development-mode: true
turnstile:
  enabled: false
  siteKey: dummy-site-key
  secretKey: dummy-secret
