name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gradle-build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    # Log in to Cloudflare Container Registry
    - name: Log in to Cloudflare Registry
      run: |
        echo "${{ secrets.CLOUDFLARE_API_TOKEN }}" | \
        docker login registry.cloudflare.com \
          --username ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} \
          --password-stdin

    # Build Docker image
    - name: Build Docker image
      run: |
        DOCKER_IMAGE="registry.cloudflare.com/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pdf-merger-service"
        docker build -t $DOCKER_IMAGE:latest .

    # Tag image with Git SHA
    - name: Tag image with commit SHA
      run: |
        DOCKER_IMAGE="registry.cloudflare.com/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pdf-merger-service"
        docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:${{ github.sha }}

    # Push all tags
    - name: Push Docker images
      run: |
        DOCKER_IMAGE="registry.cloudflare.com/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pdf-merger-service"
        docker push $DOCKER_IMAGE:latest
        docker push $DOCKER_IMAGE:${{ github.sha }}

    # Logout
    - name: Docker Logout
      run: docker logout registry.cloudflare.com
